
[project]
name = "susurrus"
version = "0.0.1"
description = "Whispering to myself"
readme = "README.md"
requires-python = ">=3.9.9"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
